# Generated by Django 5.2.6 on 2025-10-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='souscategorie',
            options={'verbose_name_plural': 'sous-categories'},
        ),
    ]
