# Generated by Django 5.2.6 on 2026-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_categorie_options_alter_souscategorie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
